### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by hammackj** [Derydoca/derydocaengine#6]
Hi, Cool engine. Could you add a license file dictating what license the code is under? GPL/MIT/PD?

**Comment by Derydoca** [comment]
Thank you! To be honest I don't know the specifics of licences, but since you are interested I will do my research and set a licence for this project soon.

**Comment by Derydoca** [comment]
Hi Hammackj. I have chosen to go with the 3-Clause BSD License due to the project's dependency on assimp which is the most restrictive license. Hope this helps! Of course, if you do any work with the Derydoca engine, I would love to hear about it!

**Comment by hammackj** [comment]
Great choice!
